### ISSUE TITLE
edit and try-again not working with RSpec

### ISSUE THREAD

**Issue by jmuheim** [ConradIrwin/pry-rescue#27]
I know, you mention something about that in your README, but I wanted to double check that it really can't be made working.

When I run a failing spec, I get into the pry console. So far, so good.

``` ruby
From: /Users/josh/Documents/Work/Sientia/iq/spec/models/user_spec.rb @ line 49 :

    44:       @user = FactoryGirl.create(:user)
    45:     end
    46: 
    47:     it "Sets empty value to 0" do
    48:       @user.update_attributes(hourly_cost_rate: "").should be_true
 => 49:       @user.hourly_cost_rate.should eq 10
    50:     end
    51: 
    52:     it "Uses Swiss Francs (CHF) as default" do
    53:       FactoryGirl.create(:user).hourly_cost_rate.currency.iso_code.should eq 'CHF'
    54:     end

RSpec::Expectations::ExpectationNotMetError: 
expected: 10
     got: #<Money fractional:0 currency:CHF>
```

But when I enter `edit-method` I get `DISABLED: Use`edit`instead.`. So I enter `edit`, but there the opened vim editor just is blank, I'm not able to edit anything of the spec itself.

On the other hand, when I fix the test from an external editor and hit `try-again`, then the test still fails - it seems that the change didn't really get reflected by the running rspec instance.

Is there anything we can do about this?

The main reason why I'm asking is this: often times I want to restart a failed (request) test using `driver: :chrome` so the website opens in chrome and I can see what's going on. So it would be really nice to have a possibility to do a `try-again` with `:driver` set to `:chrome`. Any idea on how to accomplish this?

Thanks.

**Comment by ubugnu** [comment]
The solution is:
```
edit -c
reset
.rescue rspec
```
All specs will be reloaded which is preferable.
