### ISSUE TITLE
doesn't work with Rails 4.0 + RSpec

### ISSUE THREAD

**Issue by odigity** [ConradIrwin/pry-rescue#49]
Just discovered this gem.  Followed the instructions:

1) added to Gemfile
2) ran bundle install
3) ran my specs with the "rescue" runner:
     $ rescue rake spec

But it never dropped me into Pry when one of my tests failed.

**Comment by magicalbanana** [comment]
Anyone still looking into this? It seems with rspec 3.2.0 it does not work again.

**Comment by felixbuenemann** [comment]
@magicalbanana Please open a new issue with steps to reproduce the issue.

**Comment by magicalbanana** [comment]
@felixbuenemann I have. And I will look into that.

**Comment by magicalbanana** [comment]
@felixbuenemann #81 just added it. Strange really.
