### ISSUE TITLE
pry-rescue not compatible with RSpec 3.3

### ISSUE THREAD

**Issue by tombruijn** [ConradIrwin/pry-rescue#88]
I'm getting the following error if I run rspec 3.3 using pry-rescue 1.4.2:

```
From: /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.3.1/lib/rspec/core/memoized_helpers.rb @ line 295 RSpec::ExampleGroups::Chapter6Comment::Author#subject:

 => 295: define_method(name) { __memoized.fetch_or_store(name) { super(&nil) } }

NoMethodError: undefined method `fetch_or_store' for {}:Hash
from /Users/tom/.gem/ruby/2.2.2/gems/rspec-core-3.3.1/lib/rspec/core/memoized_helpers.rb:295:in `block in let'
[1] pry(#<RSpec::ExampleGroups::MySpec>)>
```

It seems to be caused by the same kind of code as in this issue: https://github.com/rspec/rspec-core/issues/1999 . The rspec-retry gem changes the memoized variable just like pry-rescue does here: https://github.com/ConradIrwin/pry-rescue/blob/9b5e9045950e447a33ada23f689a68b5be7b6e6d/lib/pry-rescue/rspec.rb#L17-L18

**Comment by stevenhaddox** [comment]
:+1: 

I'm using Rspec 3.3.0 (via chefdk's embedded ruby & rspec/chefspec) with `pry-rescue` 1.4.2 on OS X 10.10 and encountering the same errors for each of my specs.

**Comment by stevenhaddox** [comment]
And just jumped through the motions to test on ruby 2.0.0p598 since it was listed as having no bugs, but apparently rspec 3.3.1 and pry-rescue 1.4.2 on OS X are also failing with this version of ruby with the same error. Sorry if this is redundant / overkill.

**Comment by magicalbanana** [comment]
@stevenhaddox so it's a ruby compatability issue?

**Comment by adamcrown** [comment]
:+1: I'm seeing this same error

**Comment by brain64bit** [comment]
:+1: also got error using Ubuntu 14.04, with pry-rescue 1.4.2, rspec-core 3.3.2 and ruby 2.1.2p95

**Comment by CLUSTERfoo** [comment]
:boom: same error. ruby `2.2.2p95`

**Comment by magicalbanana** [comment]
Anyone care to make a sample app? I would be happy to work on this fix.

**Comment by lukaszx0** [comment]
I can verify that I'm also having this issue on OSX, pry-rescue (1.4.2), rspec (3.3.0), ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

**Comment by magicalbanana** [comment]
So started looking at this and __memoized got changed in the RSpec::Core.

**Comment by tombruijn** [comment]
Thanks for fixing @magicalbanana !

**Comment by joelmeyerhamme** [comment]
I'm still having this issue with ruby-2.2.3 and rspec-3.3.0. Can anyone confirm?

**Comment by magicalbanana** [comment]
@joelmeyerhamme what issue?

**Comment by joelmeyerhamme** [comment]
Yay, thanks.

**Comment by joallard** [comment]
Thank you @magicalbanana !
