### ISSUE TITLE
Continue command ?

### ISSUE THREAD

**Issue by camilo1729** [ConradIrwin/pry-rescue#94]
Hello,

Nice job with this gem.Is there a continue command? kind of the one that existed before in the pry-exception_explorer gem.  For me try-again is not always an option and I would like just to continue the execution after managing interactively the exception.

Thank you

**Comment by fl0at** [comment]
I'm wondering about this too.

The peek (Ctrl-\) option is really handy, but your program will always exit afterwards, since you can't merely try-again: `Error: try-again only works in a pry session created by Pry::rescue{}`

**Comment by ConradIrwin** [comment]
Unfortunately it's not possible to `continue` as the exception has already been raised and the stack unwound. Ditto with the peek option, your program has already stopped, we just keep track of the binding and play make-believe so that it looks like it's just paused.
